export const folderActionTypes = {
  FETCH_FOLDERS_START: "FETCH_FOLDERS_START",
  FETCH_FOLDERS_SUCCESS: "FETCH_FOLDERS_SUCCESS",
  FETCH_FOLDERS_FAIL: "FETCH_FOLDERS_FAIL",
  CREATE_FOLDER_START: "CREATE_FOLDER_START",
  CREATE_FOLDER_SUCCESS: "CREATE_FOLDER_SUCCESS",
  CREATE_FOLDER_FAIL: "CREATE_FOLDER_FAIL",
  DELETE_FOLDER_START: "DELETE_FOLDER_START",
  DELETE_FOLDER_SUCCESS: "DELETE_FOLDER_SUCCESS",
  DELETE_FOLDER_FAIL: "DELETE_FOLDER_FAIL",
};
